import logging
from _thread import allocate_lock, start_new_thread
from time import sleep

import tensorboardX
from hmmlearn import _hmmc as hmmlearn_hmmc
from hmmlearn import _utils as hmmlearn_utils
from hmmlearn import hmm, base
from hmmlearn.utils import *
from sklearn.utils import check_array
from tqdm import tqdm

_log = logging.getLogger(__name__)


class TbXMonitor(base.ConvergenceMonitor):
    def __init__(self, tol, n_iter, name, model: base._BaseHMM):
        super(TbXMonitor, self).__init__(tol, n_iter, False)
        self.model = model
        self.log = tensorboardX.SummaryWriter("runs/" + name)
        self.iter = 0

    def report(self, logprob):
        """Reports to Tesorboard.

        Parameters
        ----------
        logprob : float
            The log probability of the data as computed by EM algorithm
            in the current iteration.
        """
        if self.history:
            delta = logprob - self.history[-1]
            self.log.add_scalar("delta", delta, global_step=self.iter)
        self.log.add_scalar("logprob", logprob, global_step=self.iter)
        self.history.append(logprob)

        self.log.add_image("transmat_", (self.model.transmat_ / self.model.transmat_.max())[None, :, :],
                           global_step=self.iter)
        self.log.add_image("startprob_", (self.model.startprob_ / self.model.startprob_.max())[None, None, :],
                           global_step=self.iter)
        self.log.add_image("emissionprob_",
                           (self.model.emissionprob_ / self.model.emissionprob_.max())[None, :, :],
                           global_step=self.iter)
        self.iter += 1


def iter_from_X_lengths(X, lengths, desc=None):
    if lengths is None:
        yield 0, len(X)
    else:
        n_samples = X.shape[0]
        end = np.cumsum(lengths).astype(np.int32)
        start = end - lengths
        if end[-1] > n_samples:
            raise ValueError("more than {:d} samples in lengths array {!s}"
                             .format(n_samples, lengths))

        for i in tqdm(range(len(lengths)), desc=desc):
            yield start[i], end[i]


class MultiThreadFit(hmm.MultinomialHMM):
    def __init__(self, n_components=1,
                 startprob_prior=1.0, transmat_prior=1.0,
                 algorithm="viterbi", random_state=None,
                 n_iter=10, tol=1e-2, verbose=False,
                 params="ste", init_params="ste", num_workers=8):
        super(MultiThreadFit, self).__init__(n_components=n_components,
                                             startprob_prior=startprob_prior, transmat_prior=transmat_prior,
                                             algorithm=algorithm, random_state=random_state,
                                             n_iter=n_iter, tol=tol, verbose=verbose,
                                             params=params, init_params=init_params)
        self.num_workers = num_workers

    class ThreadsafeIter:
        """Takes an iterator/generator and makes it thread-safe by
        serializing call to the `next` method of given iterator/generator.
        """

        def __init__(self, it):
            self.it = iter(it)
            self.lock = allocate_lock()

        def __iter__(self):
            return self

        def next(self):
            with self.lock:
                return next(self.it)

    def _accumulate_sufficient_statistics(self, stats, X, framelogprob,
                                          posteriors, fwdlattice, bwdlattice):
        """Updates sufficient statistics from a given sample.

        Parameters
        ----------
        stats : dict
            Sufficient statistics as returned by
            :meth:`~base._BaseHMM._initialize_sufficient_statistics`.

        X : array, shape (n_samples, n_features)
            Sample sequence.

        framelogprob : array, shape (n_samples, n_components)
            Log-probabilities of each sample under each of the model states.

        posteriors : array, shape (n_samples, n_components)
            Posterior probabilities of each sample being generated by each
            of the model states.

        fwdlattice, bwdlattice : array, shape (n_samples, n_components)
            Log-forward and log-backward probabilities.
        """

        if 't' in self.params:
            n_samples, n_components = framelogprob.shape
            # when the sample is of length 1, it contains no transitions
            # so there is no reason to update our trans. matrix estimate
            if n_samples <= 1:
                return

            log_xi_sum = np.full((n_components, n_components), -np.inf)
            hmmlearn_hmmc._compute_log_xi_sum(n_samples, n_components, fwdlattice,
                                              log_mask_zero(self.transmat_),
                                              bwdlattice, framelogprob,
                                              log_xi_sum)

        with self.stats_lock:
            stats['nobs'] += 1
            if 's' in self.params:
                stats['start'] += posteriors[0]
            if 't' in self.params:
                with np.errstate(under="ignore"):
                    stats['trans'] += np.exp(log_xi_sum)
            if 'e' in self.params:
                for t, symbol in enumerate(np.concatenate(X)):
                    stats['obs'][:, symbol] += posteriors[t]

    def fit(self, X, lengths=None):
        """Estimate model parameters.

        An initialization step is performed before entering the
        EM algorithm. If you want to avoid this step for a subset of
        the parameters, pass proper ``init_params`` keyword argument
        to estimator's constructor.

        Parameters
        ----------
        X : array-like, shape (n_samples, n_features)
            Feature matrix of individual samples.

        lengths : array-like of integers, shape (n_sequences, )
            Lengths of the individual sequences in ``X``. The sum of
            these should be ``n_samples``.

        Returns
        -------
        self : object
            Returns self.
        """
        X = check_array(X)

        if not self.monitor_.iter:
            self._init(X, lengths=lengths)
            self._check()

        for iter in range(self.n_iter):
            stats = self._initialize_sufficient_statistics()
            self.curr_logprob = 0

            iterator = self.ThreadsafeIter(iter_from_X_lengths(X, lengths, desc=f"Fitting {self.monitor_.iter}"))
            thread_exit_locks = []
            self.stats_lock = allocate_lock()
            logprob_lock = allocate_lock()

            for i in range(self.num_workers):
                thread_exit_locks.append(allocate_lock())
                start_new_thread(self.fit_thread, (), {"model": self,
                                                       "iterator": iterator,
                                                       "stats": stats,
                                                       'logprob_lock': logprob_lock,
                                                       "X": X,
                                                       "exit_lock": thread_exit_locks[-1]})

            sleep(1)
            # wait for the threads to finish
            for i, t in enumerate(thread_exit_locks):
                with t:
                    pass

            # keep model dumpable with pickle
            self.stats_lock = None

            # XXX must be before convergence check, because otherwise
            #     there won't be any updates for the case ``n_iter=1``.
            self._do_mstep(stats)
            self.monitor_.report(self.curr_logprob)
            del self.curr_logprob
            if self.monitor_.converged:
                break

        if (self.transmat_.sum(axis=1) == 0).any():
            _log.warning("Some rows of transmat_ have zero sum because no "
                         "transition from the state was ever observed.")

        return self

    def fit_thread(self, model, stats, iterator, logprob_lock, X, exit_lock):
        with exit_lock:
            while True:
                try:
                    i, j = iterator.next()
                except StopIteration:
                    break
                framelogprob = model._compute_log_likelihood(X[i:j])
                logprob, fwdlattice = model._do_forward_pass(framelogprob)
                with logprob_lock:
                    model.curr_logprob += logprob
                bwdlattice = model._do_backward_pass(framelogprob)
                posteriors = model._compute_posteriors(fwdlattice, bwdlattice)
                model._accumulate_sufficient_statistics(stats, X[i:j], framelogprob, posteriors, fwdlattice, bwdlattice)

    def score(self, X, lengths=None):
        """Compute the log probability under the model.

        Parameters
        ----------
        X : array-like, shape (n_samples, n_features)
            Feature matrix of individual samples.

        lengths : array-like of integers, shape (n_sequences, ), optional
            Lengths of the individual sequences in ``X``. The sum of
            these should be ``n_samples``.

        Returns
        -------
        logprob : float
            Log likelihood of ``X``.

        See Also
        --------
        score_samples : Compute the log probability under the model and
            posteriors.
        decode : Find most likely state sequence corresponding to ``X``.
        """
        hmmlearn_utils.check_is_fitted(self, "startprob_")
        self._check()

        X = check_array(X)
        # XXX we can unroll forward pass for speed and memory efficiency.
        self.logprob = 0

        iterator = self.ThreadsafeIter(iter_from_X_lengths(X, lengths, desc="Score"))
        thread_exit_locks = []
        logprob_lock = allocate_lock()

        for i in range(self.num_workers):
            thread_exit_locks.append(allocate_lock())
            start_new_thread(self.score_thread, (), {"model": self,
                                                     "iterator": iterator,
                                                     'logprob_lock': logprob_lock,
                                                     "X": X,
                                                     "exit_lock": thread_exit_locks[-1]})

        sleep(1)
        # wait for the threads to finish
        for i, t in enumerate(thread_exit_locks):
            with t:
                pass

        # keep model dumpable with pickle

        return self.logprob

    def score_thread(self, model, iterator, X, logprob_lock, exit_lock):
        with exit_lock:
            while True:
                try:
                    i, j = iterator.next()
                except StopIteration:
                    break
                framelogprob = model._compute_log_likelihood(X[i:j])
                logprobij, _fwdlattice = self._do_forward_pass(framelogprob)
                with logprob_lock:
                    self.logprob += logprobij
